/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessPlansRouteImport } from './routes/business-plans'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EsRouteImport } from './routes/es'
import { Route as OperationalExcellenceRouteImport } from './routes/operational-excellence'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsBusinessPlansRouteImport } from './routes/es.business-plans'
import { Route as EsContactRouteImport } from './routes/es.contact'
import { Route as EsOperationalExcellenceRouteImport } from './routes/es.operational-excellence'
import { Route as EsPrivacyRouteImport } from './routes/es.privacy'
import { Route as EsTermsRouteImport } from './routes/es.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlansRoute = BusinessPlansRouteImport.update({
  id: '/business-plans',
  path: '/business-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalExcellenceRoute = OperationalExcellenceRouteImport.update({
  id: '/operational-excellence',
  path: '/operational-excellence',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsRoute,
} as any)
const EsBusinessPlansRoute = EsBusinessPlansRouteImport.update({
  id: '/business-plans',
  path: '/business-plans',
  getParentRoute: () => EsRoute,
} as any)
const EsContactRoute = EsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EsRoute,
} as any)
const EsOperationalExcellenceRoute = EsOperationalExcellenceRouteImport.update({
  id: '/operational-excellence',
  path: '/operational-excellence',
  getParentRoute: () => EsRoute,
} as any)
const EsPrivacyRoute = EsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EsRoute,
} as any)
const EsTermsRoute = EsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-plans': typeof BusinessPlansRoute
  '/contact': typeof ContactRoute
  '/es': typeof EsRouteWithChildren
  '/operational-excellence': typeof OperationalExcellenceRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/business-plans': typeof EsBusinessPlansRoute
  '/es/contact': typeof EsContactRoute
  '/es/operational-excellence': typeof EsOperationalExcellenceRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-plans': typeof BusinessPlansRoute
  '/contact': typeof ContactRoute
  '/operational-excellence': typeof OperationalExcellenceRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/business-plans': typeof EsBusinessPlansRoute
  '/es/contact': typeof EsContactRoute
  '/es/operational-excellence': typeof EsOperationalExcellenceRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-plans': typeof BusinessPlansRoute
  '/contact': typeof ContactRoute
  '/es': typeof EsRouteWithChildren
  '/operational-excellence': typeof OperationalExcellenceRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/business-plans': typeof EsBusinessPlansRoute
  '/es/contact': typeof EsContactRoute
  '/es/operational-excellence': typeof EsOperationalExcellenceRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-plans'
    | '/contact'
    | '/es'
    | '/operational-excellence'
    | '/privacy'
    | '/terms'
    | '/es/business-plans'
    | '/es/contact'
    | '/es/operational-excellence'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-plans'
    | '/contact'
    | '/operational-excellence'
    | '/privacy'
    | '/terms'
    | '/es/business-plans'
    | '/es/contact'
    | '/es/operational-excellence'
    | '/es/privacy'
    | '/es/terms'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/business-plans'
    | '/contact'
    | '/es'
    | '/operational-excellence'
    | '/privacy'
    | '/terms'
    | '/es/business-plans'
    | '/es/contact'
    | '/es/operational-excellence'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessPlansRoute: typeof BusinessPlansRoute
  ContactRoute: typeof ContactRoute
  EsRoute: typeof EsRouteWithChildren
  OperationalExcellenceRoute: typeof OperationalExcellenceRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plans': {
      id: '/business-plans'
      path: '/business-plans'
      fullPath: '/business-plans'
      preLoaderRoute: typeof BusinessPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-excellence': {
      id: '/operational-excellence'
      path: '/operational-excellence'
      fullPath: '/operational-excellence'
      preLoaderRoute: typeof OperationalExcellenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/business-plans': {
      id: '/es/business-plans'
      path: '/business-plans'
      fullPath: '/es/business-plans'
      preLoaderRoute: typeof EsBusinessPlansRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/contact': {
      id: '/es/contact'
      path: '/contact'
      fullPath: '/es/contact'
      preLoaderRoute: typeof EsContactRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/operational-excellence': {
      id: '/es/operational-excellence'
      path: '/operational-excellence'
      fullPath: '/es/operational-excellence'
      preLoaderRoute: typeof EsOperationalExcellenceRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/privacy': {
      id: '/es/privacy'
      path: '/privacy'
      fullPath: '/es/privacy'
      preLoaderRoute: typeof EsPrivacyRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/terms': {
      id: '/es/terms'
      path: '/terms'
      fullPath: '/es/terms'
      preLoaderRoute: typeof EsTermsRouteImport
      parentRoute: typeof EsRoute
    }
  }
}

interface EsRouteChildren {
  EsBusinessPlansRoute: typeof EsBusinessPlansRoute
  EsContactRoute: typeof EsContactRoute
  EsOperationalExcellenceRoute: typeof EsOperationalExcellenceRoute
  EsPrivacyRoute: typeof EsPrivacyRoute
  EsTermsRoute: typeof EsTermsRoute
  EsIndexRoute: typeof EsIndexRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsBusinessPlansRoute: EsBusinessPlansRoute,
  EsContactRoute: EsContactRoute,
  EsOperationalExcellenceRoute: EsOperationalExcellenceRoute,
  EsPrivacyRoute: EsPrivacyRoute,
  EsTermsRoute: EsTermsRoute,
  EsIndexRoute: EsIndexRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessPlansRoute: BusinessPlansRoute,
  ContactRoute: ContactRoute,
  EsRoute: EsRouteWithChildren,
  OperationalExcellenceRoute: OperationalExcellenceRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
